# Generated by Django 4.2.26 on 2026-04-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modes', models.CharField(max_length=100)),
                ('per_km', models.FloatField(default=1.3)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=150)),
                ('modes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.mode')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('passengers', models.IntegerField(default=1)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.mode')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.route')),
            ],
        ),
    ]
