# Generated by Django 4.2.26 on 2026-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
