# Generated by Django 4.2.26 on 2026-04-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_route_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
