# Generated by Django 4.2.26 on 2026-04-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_book_price_alter_route_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
