# Generated by Django 4.2.26 on 2026-04-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_book_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='modes',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='per_km',
        ),
        migrations.CreateModel(
            name='ModeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modes', models.CharField(max_length=100)),
                ('per_km', models.FloatField(default=1.1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.mode')),
            ],
        ),
    ]
