# Generated by Django 4.2.26 on 2026-04-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_rename_modes_mode_name_remove_mode_per_km_modetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='name',
            new_name='modes',
        ),
        migrations.RenameField(
            model_name='modetype',
            old_name='per_km',
            new_name='price_per_km',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='modes',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='modetype',
            name='name',
        ),
        migrations.AddField(
            model_name='modetype',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modetype',
            name='modes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.mode'),
        ),
    ]
