# Generated by Django 4.2.26 on 2026-04-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_rename_name_mode_modes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='via',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
