# Generated by Django 4.2.26 on 2026-04-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_alter_route_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.modetype'),
        ),
    ]
