# Generated by Django 4.2.26 on 2026-04-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_alter_route_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.modetype'),
        ),
    ]
