# Generated by Django 4.2.26 on 2026-04-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_alter_book_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='service',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.route')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='seat',
            field=models.ManyToManyField(to='travelapp.seat'),
        ),
    ]
