# Generated by Django 4.2.26 on 2026-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_remove_route_service_seat_book_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('route', 'seat_no')},
        ),
    ]
