# Generated by Django 4.2.26 on 2026-04-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_alter_seat_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='seat',
        ),
        migrations.AddField(
            model_name='book',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.seat'),
        ),
    ]
