# Generated by Django 4.2.26 on 2026-04-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_alter_book_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seat',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.modetype'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('route', 'seat_no', 'mode')},
        ),
    ]
