# Generated by Django 4.2.26 on 2026-04-28 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelapp', '0014_alter_seat_unique_together_seat_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.seat'),
        ),
    ]
