# Generated by Django 4.2.26 on 2026-04-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.seat'),
        ),
    ]
